/**
 * Every identifier Rich Content allocates. All of them are generated by the
 * capability's ID factory; a consumer never mints one.
 */
export type RichContentId = string;
export type AtomId = string;
export type DisplayLineId = string;
export type DisplaySegmentId = string;
export type ListId = string;
