/**
 * Every panel this application intends to have.
 *
 * Hand-written, and the plan rather than the inventory. A key here whose file
 * does not exist yet renders the placeholder, which is what lets a panel be
 * designed before it is built. `key-vocabulary-matches-the-tree` holds the other
 * direction: a panel that exists must be named here.
 *
 * `"empty"` is deliberately absent from the lenses. Nothing being inspected is a
 * state of the model rather than a panel, so it belongs to the hand-written type
 * that unions the two.
 */

/** Every context-panel view. */
export const CONTEXT_IDS = [
  "agents.automations",
  "agents.behaviour",
  "agents.context-persona",
  "agents.do-this",
  "agents.health",
  "agents.personas",
  "agents.tasks",
  "agents.tools",
  "agents.when",
  "agents.work",
  "analysis.chart",
  "analysis.fields",
  "analysis.formula",
  "analysis.variables",
  "library.analyses",
  "library.authoring-body",
  "library.authoring-design",
  "library.authoring-insert",
  "library.authoring-variables",
  "library.bring-in",
  "library.contexts",
  "library.create",
  "library.findings",
  "library.inquiry",
  "library.recent-newtab",
  "library.recent-templates",
  "library.resources",
  "library.template",
  "library.template-kinds",
  "library.templates",
  "library.templates-newtab",
  "library.threads",
  "overview.agents",
  "overview.analysis",
  "overview.context",
  "overview.deck",
  "overview.document",
  "overview.project",
  "overview.research",
  "overview.spreadsheet",
  "overview.templates-authoring",
  "overview.templates-library",
  "project.activity",
  "project.contexts",
  "project.history",
  "project.mentions",
  "project.people",
  "project.resources",
  "project.tasks",
  "project.templates",
  "project.variables",
  "project.variables-create",
  "research.context",
  "research.findings",
  "research.history",
  "research.inquiry",
  "research.sources",
  "research.trace",
  "resource.comments-deck",
  "resource.comments-document",
  "resource.comments-sheet",
  "resource.context-deck",
  "resource.context-document",
  "resource.context-sheet",
  "resource.dependencies",
  "resource.find-deck",
  "resource.find-document",
  "resource.find-sheet",
  "resource.insert-deck",
  "resource.insert-document",
  "resource.insert-sheet",
  "resource.layers",
  "resource.layout-layouts",
  "resource.layout-objects",
  "resource.layout-theme",
  "resource.layouts",
  "resource.named-ranges",
  "resource.navigator",
  "resource.notes",
  "resource.objects",
  "resource.page",
  "resource.print",
  "resource.slides",
  "resource.styles-document",
  "resource.styles-sheet",
  "resource.theme",
  "scope.add",
  "scope.contents",
  "scope.contexts",
  "scope.knowledge",
  "scope.used-by"
] as const;

export type ContextId = (typeof CONTEXT_IDS)[number];

/** Every inspector lens. */
export const INSPECTION_KEYS = [
  "agents.agent-action",
  "agents.automation",
  "agents.behaviour-section",
  "agents.last-fired",
  "agents.model",
  "agents.persona",
  "agents.refresh-action",
  "agents.schedule-trigger",
  "agents.task",
  "agents.task-behaviour",
  "agents.task-results",
  "agents.tool",
  "agents.trigger",
  "agents.what-it-can-look-up",
  "analysis.analysis",
  "analysis.bar-graph",
  "analysis.bars",
  "analysis.bars-multi",
  "analysis.cell",
  "analysis.cells-multi",
  "analysis.chart",
  "analysis.column",
  "analysis.columns-multi",
  "analysis.data-button",
  "analysis.filter",
  "analysis.labels",
  "analysis.limit",
  "analysis.mark",
  "analysis.placement",
  "analysis.relationship",
  "analysis.row",
  "analysis.rows-multi",
  "analysis.sort",
  "analysis.table-graph",
  "analysis.variable",
  "analysis.x-axis",
  "analysis.y-axis",
  "collaboration.comment",
  "collaboration.mention",
  "collaboration.people",
  "collaboration.person",
  "copilot.conversation",
  "copilot.home",
  "copilot.task",
  "copilot.what-it-can-see",
  "library.body-entity",
  "library.connect",
  "library.new-deck",
  "library.new-document",
  "library.new-spreadsheet",
  "library.recent-item",
  "library.start-from-template",
  "library.template",
  "library.template-variable",
  "library.upload",
  "library.use-template",
  "project.activity",
  "project.connector",
  "project.file",
  "project.project",
  "project.resource",
  "research.accepted-finding",
  "research.hypothesis",
  "research.proposed-finding",
  "research.question",
  "research.research-thread",
  "research.source",
  "research.thread",
  "research.tool-call",
  "resource.cell",
  "resource.cell-with-formula",
  "resource.chart",
  "resource.deck",
  "resource.document",
  "resource.element",
  "resource.error-cell",
  "resource.footer",
  "resource.formula",
  "resource.header",
  "resource.layout",
  "resource.link",
  "resource.locked-element",
  "resource.multi-selection",
  "resource.named-range",
  "resource.named-style-deck",
  "resource.named-style-document",
  "resource.named-style-sheet",
  "resource.placeholder",
  "resource.prompt-block",
  "resource.range",
  "resource.slide",
  "resource.speaker-notes",
  "resource.spill",
  "resource.spreadsheet",
  "resource.table",
  "resource.text-block-deck",
  "resource.text-block-document",
  "resource.text-selection",
  "resource.theme",
  "scope.context",
  "scope.generated-block",
  "scope.include-context",
  "scope.include-everything",
  "scope.lattice-node",
  "scope.resolved-resource",
  "scope.search-result",
  "scope.take-out-kind"
] as const;

export type InspectionKey = (typeof INSPECTION_KEYS)[number];

export const isContextId = (value: string): value is ContextId =>
  (CONTEXT_IDS as readonly string[]).includes(value);

export const isInspectionKey = (value: string): value is InspectionKey =>
  (INSPECTION_KEYS as readonly string[]).includes(value);
