#!/usr/bin/env bash
# Compare candidate models across the whole intelligence group, grouped by CAST.
#
# The per-suite reports answer "how did this suite behave". This answers the
# question above them: which model should serve which cast.
#
# Cast is the unit because it is the only thing the application chooses. Code
# asks for (purpose, strength, speed, cost); configuration decides which model
# that resolves to. So "the best model" is not one answer — it is one answer per
# cast, and a table that averaged across casts would recommend a single model for
# work with genuinely different shapes.
#
# Each input log is one full `run.sh intelligence` under one configuration.
#
# Usage:
#   ./dev-test/model-report.sh RUN.log [RUN.log ...]
set -euo pipefail
[[ $# -ge 1 ]] || { echo "usage: model-report.sh RUN.log [...]" >&2; exit 2; }

# Rates come from dev-test/model-prices.tsv when it exists (refresh it with
# ./dev-test/model-prices.sh). The inline list below is the fallback for a
# machine with no catalogue fetched; a model in neither prices at 0.00, which
# reads as free rather than unknown, so keep the file fresh before a sweep.
PRICEFILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/model-prices.tsv"
read -r -d '' PRICES <<'EOF' || true
openai/gpt-5.6-luna 0.50 3.00
openai/gpt-5.1 1.25 10.00
openai/gpt-5-mini 0.25 2.00
openai/gpt-4.1-mini 0.40 1.60
openai/gpt-4.1-nano 0.10 0.40
openai/gpt-4o-mini 0.15 0.60
openai/gpt-oss-120b 0.037 0.17
google/gemini-3-flash-preview 0.50 3.00
google/gemini-2.5-flash 0.30 2.50
anthropic/claude-haiku-4.5 1.00 5.00
anthropic/claude-3.5-sonnet 3.00 15.00
openai/text-embedding-3-small 0.02 0.00
EOF
if [[ -f "$PRICEFILE" ]]; then PRICES="$(cat "$PRICEFILE")"; fi

extract() {
  sed 's/\x1b\[[0-9;]*m//g' "$1" | awk -v prices="$PRICES" '
BEGIN {
  n = split(prices, L, "\n")
  for (i = 1; i <= n; i++) if (split(L[i], p, " ") == 3) { IN[p[1]] = p[2]; OUT[p[1]] = p[3]; KNOWN[p[1]] = 1 }
}
/^═══ .* ═══$/ { suite = $2; next }
/^  ✓ all checks passed$/ { passed++; next }
/^  ✗ [0-9]+ check\(s\) failed$/ { failedsuites = failedsuites " " suite; next }
/call: / {
  rest = substr($0, index($0, "call: ")); nf = split(rest, F, " ")
  op = F[2]
  model = (F[3] ~ /^\[/) ? F[4] : F[3]
  tot = 0; pr = 0; co = 0; re = 0; secs = 0; cast = "-"
  for (i = 1; i <= nf; i++) {
    if (F[i] == "cast")                              cast = F[i+1]
    if (F[i] == "tokens")                            tot = F[i-1] + 0
    if (F[i] ~ /^prompt,?$/)                       { t = F[i-1]; gsub(/\(/, "", t); pr = t + 0 }
    if (F[i] ~ /^completion/)                        co = F[i-1] + 0
    if (F[i] ~ /^reasoning[),]*$/)                   re = F[i-1] + 0
    if (F[i] == "—")                               { d = F[i+1]; sub(/,$/, "", d); secs = dur(d) }
  }
  sub(/,$/, "", cast)
  if (co == 0 && tot > pr) co = tot - pr
  # A model absent from the rate table costs 0 arithmetically, which is
  # indistinguishable from a genuinely free model. They mean opposite things, so
  # the absent case is recorded and reported rather than silently rendered as 0.
  if (!(model in KNOWN)) UNPRICED[model] = 1
  usd = pr/1000000 * IN[model] + co/1000000 * OUT[model]

  TOTCALLS++; TOTSEC += secs; TOTUSD += usd; TOTTOK += pr + co; TOTRE += re
  # A run that "passed" on its fallback has not shown the substituted model works.
  # Both of these have to be visible or a sweep will credit the wrong model.
  if ($0 ~ /, attempt /) FELLBACK++
  if ($0 ~ /FAILED/) CALLFAIL++
  k = cast SUBSEP op SUBSEP model
  if (!(k in seen)) { seen[k] = 1; keys[++nk] = k }
  C[k]++; P[k] += pr; O[k] += co; R[k] += re; S[k] += secs; U[k] += usd
  next
}
END {
  unpriced = ""
  for (m in UNPRICED) unpriced = unpriced " " m
  printf "RUN\t%d\t%s\t%d\t%d\t%d\t%.3f\t%.6f\t%d\t%d\t%s\n", passed, (failedsuites == "" ? "-" : failedsuites), TOTCALLS, TOTTOK, TOTRE, TOTSEC, TOTUSD, CALLFAIL, FELLBACK, (unpriced == "" ? "-" : unpriced)
  for (i = 1; i <= nk; i++) {
    k = keys[i]; split(k, p, SUBSEP)
    printf "CAST\t%s\t%s\t%s\t%d\t%d\t%d\t%d\t%.3f\t%.6f\n", p[1], p[2], p[3], C[k], P[k], O[k], R[k], S[k], U[k]
  }
}
function dur(d) {
  if (d ~ /ms$/)        { sub(/ms$/, "", d); return d / 1000 }
  if (d ~ /µs$/)        { sub(/µs$/, "", d); return d / 1000000 }
  if (d ~ /m[0-9.]+s$/) { split(d, mm, "m"); sub(/s$/, "", mm[2]); return mm[1] * 60 + mm[2] }
  if (d ~ /s$/)         { sub(/s$/, "", d); return d + 0 }
  return 0
}
'
}

NRUNS=$#
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
for lg in "$@"; do extract "$lg" > "$TMP/$(basename "$lg").tsv"; done

printf '# Model choice, by cast\n\n'
printf 'Date: %s\n\n' "$(date -u +%Y-%m-%d)"
printf 'Generated by [dev-test/model-report.sh](../../dev-test/model-report.sh) from one\n'
printf '`run.sh intelligence` log per candidate. Every number is measured: token counts\n'
printf 'are the provider'"'"'s own per-call usage, cost is those counts at each model'"'"'s\n'
printf 'published rate.\n\n'

printf 'A **cast** is what the application asks for — `purpose/strength/speed/cost`.\n'
printf 'Code never names a model; configuration maps each cast to one. So "which model\n'
printf 'is best" has one answer per cast, not one answer overall, and this document is\n'
printf 'organised that way.\n\n'

printf '## Whole-run totals\n\n'
printf '| Configuration | Suites passed | Failed | Calls | Tokens | Reasoning | Model time | Cost (USD) | Call errors | Fallbacks |\n'
printf '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n'
for f in "$TMP"/*.tsv; do
  name="$(basename "$f" .log.tsv)"
  awk -F'\t' -v n="$name" '$1=="RUN" {
    cost = ($11 == "-") ? sprintf("%.5f", $8) : sprintf("%.5f ⚠unpriced:%s", $8, $11)
    printf "| `%s` | %d | %s | %d | %d | %d | %.1fs | %s | %d | %d |\n", n, $2, $3, $4, $5, $6, $7, cost, $9, $10
  }' "$f"
done
echo

# Models whose whole run passed every suite. Only these are eligible to "win" a
# cast: a model that is cheap and fast at one cast while failing a suite has not
# earned a recommendation, and ranking it alongside the others would imply it had.
QUALIFIED="$(awk -F'\t' '$1=="RUN" && $3=="-" { print FILENAME }' "$TMP"/*.tsv \
  | xargs -r -n1 basename | sed 's/\.log\.tsv$//' | tr '\n' ' ')"

printf '## By cast\n\n'
CASTS="$(awk -F'\t' '$1=="CAST" { print $2"\t"$3 }' "$TMP"/*.tsv | sort -u)"
while IFS=$'\t' read -r cast op; do
  [[ -n "$cast" ]] || continue
  printf '### `%s` — %s\n\n' "$cast" "$op"
  # Totals AND per-call. Totals alone invite being read as an average — a
  # 58-call cast showing "26128 input" is 450 tokens a call, and the two numbers
  # lead to opposite conclusions about how heavy a call is.
  printf '| Model | Calls | Input | Output | Reasoning | Time | Cost (USD) | In/call | s/call | USD/call |\n'
  printf '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n'
  # One row per MODEL, summed over the runs it served in. A model counts as
  # qualified only if every run it served in passed every suite — being cheap at
  # a cast is not a recommendation when the run did not pass.
  for f in "$TMP"/*.tsv; do
    run="$(basename "$f" .log.tsv)"
    ok="1"; case " $QUALIFIED " in *" $run "*) ;; *) ok="0" ;; esac
    awk -F'\t' -v c="$cast" -v o="$op" -v ok="$ok" '
      $1=="CAST" && $2==c && $3==o {
        printf "%s\t%s\t%d\t%d\t%d\t%d\t%.3f\t%.6f\n", $4, ok, $5, $6, $7, $8, $9, $10 }
    ' "$f"
  done | awk -F"\t" -v nruns="$NRUNS" '
    { m=$1; runs[m]++; if ($2=="0") bad[m]=1
      C[m]+=$3; P[m]+=$4; O[m]+=$5; R[m]+=$6; S[m]+=$7; U[m]+=$8
      if (!(m in seen)) { seen[m]=1; order[++n]=m } }
    END {
      # Sort model names so the table reads the same on every regeneration. Array
      # iteration order is unspecified in awk and would otherwise churn the diff.
      for (i=2; i<=n; i++) { key=order[i]; j=i-1
        while (j>=1 && order[j] > key) { order[j+1]=order[j]; j-- }
        order[j+1]=key }
      for (i=1; i<=n; i++) {
        m = order[i]
        # A ⚠ only means something where the ladder actually varied the cast. With
        # one model across every run, the model is not what the run was testing —
        # flagging it for a failure elsewhere in that run would read as an
        # accusation the data does not support.
        mark = (n > 1 && (m in bad)) ? " ⚠" : ""
        printf "| `%s`%s | %d | %d | %d | %d | %.2fs | %.6f | %d | %.2fs | %.6f |\n",
          m, mark, C[m], P[m], O[m], R[m], S[m], U[m],
          (C[m] ? P[m]/C[m] : 0), (C[m] ? S[m]/C[m] : 0), (C[m] ? U[m]/C[m] : 0)
        if (!(m in bad)) {
          if (bestc == "" || U[m] < bestcv) { bestc = m; bestcv = U[m] }
          if (bestt == "" || S[m] < besttv) { bestt = m; besttv = S[m] }
        }
      }
      if (n == 1) {
        printf "\nOne model across every run, so these are totals over all %d runs rather than\none. The ladder did not vary this cast: the model it substituted was never the\nprimary here, and there is nothing to choose between.\n", nruns
      } else if (bestc != "") {
        printf "\nAmong models whose run passed every suite: cheapest `%s` (%.6f USD), fastest `%s` (%.2fs).\n",
          bestc, bestcv, bestt, besttv
      } else {
        printf "\nNo model serving this cast passed every suite.\n"
      }
    }'
  echo
done <<< "$CASTS"

printf 'A ⚠ marks a model whose run failed at least one suite. Its numbers are shown\n'
printf 'because they are real, and it is excluded from "cheapest" and "fastest" because\n'
printf 'being cheap at a cast is not a recommendation when the run did not pass.\n\n'

printf 'A cast served by the same model in every run reads identically across the table.\n'
printf 'That is not a bug in the comparison — it says the ladder did not vary that cast,\n'
printf 'because the substituted model was never its primary.\n'
