package agent

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/gccurtis/taurus-omega/core/capability/intelligence"
	"github.com/gccurtis/taurus-omega/core/capability/persona"
	"github.com/gccurtis/taurus-omega/core/platform/job"
)

const (
	// JobTypeRun is the sole durable job that starts or resumes one Agent task
	// run. Its payload identifies an already-persisted task and run; it never
	// carries a user prompt, Project selection, or tool list.
	JobTypeRun = "agent.task.run"

	maxTaskNotes = 64
	maxTaskTodos = 128
	maxTaskPlans = 16
	maxTaskText  = 8 * 1024
)

// TaskMode selects the durable workflow a task will run. Ask remains transient
// and deliberately has no Task mode.
type TaskMode string

const (
	TaskModePlan   TaskMode = "plan"
	TaskModeAction TaskMode = "action"
)

// TaskState names the small first lifecycle. A worker settles the state from a
// validated PlanDraft or ExecutionReport; a model never sets it directly.
type TaskState string

const (
	TaskStateQueued             TaskState = "queued"
	TaskStateRunning            TaskState = "running"
	TaskStateWaiting            TaskState = "waiting"
	TaskStateCompleted          TaskState = "completed"
	TaskStatePartiallyCompleted TaskState = "partially_completed"
	TaskStateFailed             TaskState = "failed"
	TaskStateCanceled           TaskState = "canceled"
)

// TodoState is one task-local work-list state. To-dos organize an agent's
// workflow; they are not target-resource changes or proof that an effect ran.
type TodoState string

const (
	TodoStateOpen     TodoState = "open"
	TodoStateDoing    TodoState = "doing"
	TodoStateDone     TodoState = "done"
	TodoStateBlocked  TodoState = "blocked"
	TodoStateCanceled TodoState = "canceled"
)

// PersonaSnapshot remains an Agent-facing alias while the Persona capability
// owns the persisted identity and immutable version model.
type PersonaSnapshot = persona.Snapshot

// Todo is one bounded Task-owned item. CreatedBy is "user" or "agent" and is
// retained to make a task's working plan intelligible after a later run.
type Todo struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	State     TodoState `json:"state"`
	CreatedBy string    `json:"createdBy"`
	Detail    string    `json:"detail,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TaskPlan is a task-local working plan. It is intentionally distinct from the
// validated reviewable PlanRevision produced by Plan mode.
type TaskPlan struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
}

// PlanDraft is the structured, reviewable content generated by Plan mode. The
// service stores it in a PlanRevision; a working TaskPlan remains a lighter
// private planning aid for either mode.
type PlanDraft struct {
	Title           string     `json:"title"`
	Objective       string     `json:"objective"`
	Summary         string     `json:"summary"`
	Assumptions     []string   `json:"assumptions"`
	OpenQuestions   []string   `json:"openQuestions"`
	SuccessCriteria []string   `json:"successCriteria"`
	Steps           []PlanStep `json:"steps"`
	Risks           []PlanRisk `json:"risks"`
	Citations       []Citation `json:"citations"`
}

type PlanStep struct {
	ID                 string     `json:"id"`
	Title              string     `json:"title"`
	Description        string     `json:"description"`
	Rationale          string     `json:"rationale"`
	DependsOnStepIDs   []string   `json:"dependsOnStepIds"`
	Deliverables       []string   `json:"deliverables"`
	CompletionCriteria []string   `json:"completionCriteria"`
	Citations          []Citation `json:"citations"`
}

type PlanRisk struct {
	Description string `json:"description"`
	Mitigation  string `json:"mitigation,omitempty"`
}

type PlanRevision struct {
	ID         string     `json:"id"`
	Revision   int        `json:"revision"`
	Draft      PlanDraft  `json:"draft"`
	State      string     `json:"state"`
	CreatedAt  time.Time  `json:"createdAt"`
	AcceptedAt *time.Time `json:"acceptedAt,omitempty"`
}

// TaskWorkspace is the bounded persistent working material a Plan or Action
// agent can retrieve on a later run. Notes never become factual evidence.
type TaskWorkspace struct {
	Notes         []string   `json:"notes,omitempty"`
	Todos         []Todo     `json:"todos,omitempty"`
	WorkingPlans  []TaskPlan `json:"workingPlans,omitempty"`
	OpenQuestions []string   `json:"openQuestions,omitempty"`
}

// TaskRun is one durable attempt to run a task. A new resume creates a new run
// rather than pretending a provider conversation can survive a process restart.
type TaskRun struct {
	ID         string          `json:"id"`
	State      TaskState       `json:"state"`
	Attempt    int             `json:"attempt"`
	StartedAt  *time.Time      `json:"startedAt,omitempty"`
	FinishedAt *time.Time      `json:"finishedAt,omitempty"`
	Failure    string          `json:"failure,omitempty"`
	Result     json.RawMessage `json:"result,omitempty"`
	Usage      Usage           `json:"usage"`
}

// Task stores the immutable original request and mutable workspace for one
// durable Plan or Action. ProjectID and RequesterID are assigned by application
// code, never model arguments or a task tool input.
type Task struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"projectId"`
	RequesterID string    `json:"requesterId"`
	Mode        TaskMode  `json:"mode"`
	State       TaskState `json:"state"`
	Objective   string    `json:"objective"`
	// TargetDocumentID scopes a task to one document (the document a chat is
	// pinned to, or an explicit targetDocumentId on create); empty means the task
	// is not tied to a specific document.
	TargetDocumentID string          `json:"targetDocumentId,omitempty"`
	Context          []ContextItem   `json:"context,omitempty"`
	Persona          PersonaSnapshot `json:"persona"`
	Workspace        TaskWorkspace   `json:"workspace"`
	Plans            []PlanRevision  `json:"plans,omitempty"`
	Runs             []TaskRun       `json:"runs"`
	CreatedAt        time.Time       `json:"createdAt"`
	UpdatedAt        time.Time       `json:"updatedAt"`
}

// RunPayload is the only job payload accepted by RunJob. The worker reloads the
// actual Task before doing anything, so a queued payload cannot broaden scope.
type RunPayload struct {
	TaskID string `json:"taskId"`
	RunID  string `json:"runId"`
}

// TaskStore persists whole Task records. The first implementation keeps the
// aggregate small and updates it atomically; individual task tools load, verify
// the captured Project/Task, mutate a bounded field, then store it back.
// BeginTaskRun atomically transitions a queued task to running so two workers
// cannot claim the same task. BumpHeartbeat keeps a running task alive during
// long execution; ReapStaleTasks recovers tasks stuck in running after a crash.
type TaskStore interface {
	CreateTask(Task) error
	TaskByID(string) (Task, error)
	TasksByProject(string) ([]Task, error)
	TasksByPersona(string, string) ([]Task, error)
	TasksByDocument(projectID, documentID string) ([]Task, error)
	UpdateTask(Task) error
	BeginTaskRun(taskID, runID string, content []byte, now time.Time) (Task, error)
	BumpHeartbeat(taskID string, now time.Time) error
	ReapStaleTasks(before time.Time) error
}

// Tasks creates and retrieves durable tasks and exports their fixed task-local
// tool bindings. It is safe for concurrent callers when the supplied store is.
type Tasks struct {
	store    TaskStore
	enqueuer job.Enqueuer
	now      func() time.Time
}

// StartReaper begins periodically transitioning tasks stuck in running back to
// queued. It runs until ctx is cancelled, so it stops cleanly on shutdown rather
// than looping forever and touching the store as it closes. Call once at startup.
func (t *Tasks) StartReaper(ctx context.Context, interval, staleAfter time.Duration) {
	go func() {
		ticker := time.NewTicker(interval)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				_ = t.store.ReapStaleTasks(t.now().Add(-staleAfter))
			}
		}
	}()
}

var (
	ErrTaskNotFound     = errors.New("agent task: not found")
	ErrInvalidTask      = errors.New("agent task: invalid task")
	ErrTaskNotRunnable  = errors.New("agent task: run is not queued")
	ErrTaskProjectScope = errors.New("agent task: task is outside the current Project")
)

// TaskOptions selects application-owned behavior for every new task.
type TaskOptions struct {
	Enqueuer job.Enqueuer
}

// NewTasks constructs the durable Task service. A nil Enqueuer is valid for
// focused tests, but production Plan/Action construction requires one to make
// the newly persisted task runnable.
func NewTasks(store TaskStore, opts TaskOptions) (*Tasks, error) {
	if store == nil {
		return nil, errors.New("agent task: store is required")
	}
	return &Tasks{store: store, enqueuer: opts.Enqueuer, now: time.Now}, nil
}

// Create records a queued Task and its first queued TaskRun. The task is stored
// before enqueueing so a job always identifies canonical durable state.
func (t *Tasks) Create(scope Scope, requesterID string, mode TaskMode, objective string, items []ContextItem, personaSnapshot PersonaSnapshot, targetDocumentID string) (Task, error) {
	if strings.TrimSpace(scope.ProjectID) == "" {
		return Task{}, ErrInvalidScope
	}
	if strings.TrimSpace(requesterID) == "" || !validTaskMode(mode) || strings.TrimSpace(objective) == "" || len(objective) > maxTaskText || !validPersonaSnapshot(personaSnapshot) {
		return Task{}, ErrInvalidTask
	}
	if _, err := contextMessage(items); err != nil {
		return Task{}, err
	}
	now := t.now().UTC()
	run := TaskRun{ID: newTaskID(), State: TaskStateQueued, Attempt: 1}
	task := Task{
		ID: newTaskID(), ProjectID: scope.ProjectID, RequesterID: requesterID,
		Mode: mode, State: TaskStateQueued, Objective: objective, TargetDocumentID: strings.TrimSpace(targetDocumentID),
		Context: append([]ContextItem(nil), items...),
		Persona: clonePersonaSnapshot(personaSnapshot), Runs: []TaskRun{run}, CreatedAt: now, UpdatedAt: now,
	}
	if err := t.store.CreateTask(task); err != nil {
		return Task{}, err
	}
	if t.enqueuer != nil {
		if _, err := t.enqueuer.Enqueue(context.Background(), JobTypeRun, RunPayload{TaskID: task.ID, RunID: run.ID}); err != nil {
			return Task{}, fmt.Errorf("agent task: enqueue run: %w", err)
		}
	}
	return task, nil
}

// Get returns one Task after proving it belongs to the trusted current Project.
func (t *Tasks) Get(scope Scope, id string) (Task, error) {
	task, err := t.store.TaskByID(id)
	if err != nil {
		return Task{}, err
	}
	if task.ProjectID != scope.ProjectID {
		return Task{}, ErrTaskProjectScope
	}
	return task, nil
}

// List returns the current Project's durable tasks in stable creation order.
func (t *Tasks) List(scope Scope) ([]Task, error) {
	if strings.TrimSpace(scope.ProjectID) == "" {
		return nil, ErrInvalidScope
	}
	tasks, err := t.store.TasksByProject(scope.ProjectID)
	if err != nil {
		return nil, err
	}
	sort.Slice(tasks, func(i, j int) bool { return tasks[i].CreatedAt.Before(tasks[j].CreatedAt) })
	return tasks, nil
}

// ListByDocument returns the current Project's tasks scoped to one document — the
// tasks whose TargetDocumentID matches — in stable creation order. Tasks with no
// target document are excluded.
func (t *Tasks) ListByDocument(scope Scope, documentID string) ([]Task, error) {
	if strings.TrimSpace(scope.ProjectID) == "" {
		return nil, ErrInvalidScope
	}
	if strings.TrimSpace(documentID) == "" {
		return nil, ErrInvalidTask
	}
	tasks, err := t.store.TasksByDocument(scope.ProjectID, documentID)
	if err != nil {
		return nil, err
	}
	sort.Slice(tasks, func(i, j int) bool { return tasks[i].CreatedAt.Before(tasks[j].CreatedAt) })
	return tasks, nil
}

// ListByPersona returns the Persona-attributed task history inside the current
// Project. Task remains the canonical history record; Persona does not keep a
// second mutable list of task copies.
func (t *Tasks) ListByPersona(scope Scope, personaID string) ([]Task, error) {
	if strings.TrimSpace(personaID) == "" {
		return nil, ErrInvalidTask
	}
	if strings.TrimSpace(scope.ProjectID) == "" {
		return nil, ErrInvalidScope
	}
	tasks, err := t.store.TasksByPersona(scope.ProjectID, personaID)
	if err != nil {
		return nil, err
	}
	sort.Slice(tasks, func(i, j int) bool { return tasks[i].CreatedAt.Before(tasks[j].CreatedAt) })
	return tasks, nil
}

// AcceptPlan records review acceptance for one exact generated PlanRevision.
// It is deliberately not an execution command: Action may use a plan later but
// remains directly requestable without one.
func (t *Tasks) AcceptPlan(scope Scope, taskID, planID string) (Task, error) {
	task, err := t.Get(scope, taskID)
	if err != nil {
		return Task{}, err
	}
	if task.Mode != TaskModePlan {
		return Task{}, ErrInvalidTask
	}
	index := -1
	for i := range task.Plans {
		if task.Plans[i].ID == planID {
			index = i
			break
		}
	}
	if index < 0 || task.Plans[index].State != "draft" {
		return Task{}, ErrInvalidTask
	}
	now := t.now().UTC()
	task.Plans[index].State, task.Plans[index].AcceptedAt = "accepted", &now
	task.UpdatedAt = now
	if err := t.store.UpdateTask(task); err != nil {
		return Task{}, err
	}
	return task, nil
}

// BeginRun moves one queued run into running. The later workflow worker calls
// FinishRun with its validated final result.
func (t *Tasks) BeginRun(scope Scope, payload RunPayload) (Task, TaskRun, error) {
	task, err := t.Get(scope, payload.TaskID)
	if err != nil {
		return Task{}, TaskRun{}, err
	}
	index := taskRunIndex(task.Runs, payload.RunID)
	if index < 0 || task.Runs[index].State != TaskStateQueued || task.State != TaskStateQueued {
		return Task{}, TaskRun{}, ErrTaskNotRunnable
	}
	now := t.now().UTC()
	task.State = TaskStateRunning
	task.Runs[index].State = TaskStateRunning
	task.Runs[index].StartedAt = &now
	task.UpdatedAt = now
	raw, err := json.Marshal(task)
	if err != nil {
		return Task{}, TaskRun{}, err
	}
	updated, err := t.store.BeginTaskRun(payload.TaskID, payload.RunID, raw, now)
	if err != nil {
		return Task{}, TaskRun{}, err
	}
	ri := taskRunIndex(updated.Runs, payload.RunID)
	if ri < 0 {
		return Task{}, TaskRun{}, ErrTaskNotRunnable
	}
	return updated, updated.Runs[ri], nil
}

// FinishRun stores the workflow's validated report and settles both run and
// task state. Only Plan/Action service code uses it after reconciling outputs.
func (t *Tasks) FinishRun(scope Scope, taskID, runID string, state TaskState, result json.RawMessage, usage Usage, failure string) error {
	task, err := t.Get(scope, taskID)
	if err != nil {
		return err
	}
	index := taskRunIndex(task.Runs, runID)
	if index < 0 || task.Runs[index].State != TaskStateRunning || !terminalTaskState(state) && state != TaskStateWaiting {
		return ErrInvalidTask
	}
	now := t.now().UTC()
	task.State, task.UpdatedAt = state, now
	task.Runs[index].State, task.Runs[index].FinishedAt = state, &now
	task.Runs[index].Result, task.Runs[index].Usage, task.Runs[index].Failure = append(json.RawMessage(nil), result...), usage, failure
	return t.store.UpdateTask(task)
}

// ToolBindings returns the fixed task-local library for a loaded Task. Every
// handler captures trusted Project/Task identities, so model JSON cannot read
// or mutate a different task.
func (t *Tasks) ToolBindings(scope Scope, task Task) []intelligence.ToolBinding {
	return []intelligence.ToolBinding{
		t.contextTool(scope, task.ID), t.noteTool(scope, task.ID), t.todoListTool(scope, task.ID),
		t.todoCreateTool(scope, task.ID), t.todoUpdateTool(scope, task.ID), t.planListTool(scope, task.ID),
		t.planGetTool(scope, task.ID), t.planCreateTool(scope, task.ID),
	}
}

func validTaskMode(mode TaskMode) bool { return mode == TaskModePlan || mode == TaskModeAction }

func validPersonaSnapshot(snapshot PersonaSnapshot) bool {
	return strings.TrimSpace(snapshot.ID) != "" && snapshot.Version > 0 && strings.TrimSpace(snapshot.Name) != "" && strings.TrimSpace(snapshot.Instructions) != ""
}

func clonePersonaSnapshot(snapshot PersonaSnapshot) PersonaSnapshot {
	snapshot.ContextReferences = append([]string(nil), snapshot.ContextReferences...)
	return snapshot
}

func terminalTaskState(state TaskState) bool {
	return state == TaskStateCompleted || state == TaskStatePartiallyCompleted || state == TaskStateFailed || state == TaskStateCanceled
}

func taskRunIndex(runs []TaskRun, id string) int {
	for i := range runs {
		if runs[i].ID == id {
			return i
		}
	}
	return -1
}

func newTaskID() string {
	bytes := make([]byte, 16)
	_, _ = rand.Read(bytes)
	return hex.EncodeToString(bytes)
}

// MemoryTaskStore provides durable-aggregate semantics for unit tests without a
// database. It returns JSON copies so callers cannot mutate stored state.
type MemoryTaskStore struct {
	mu    sync.Mutex
	tasks map[string]Task
}

// NewMemoryTaskStore returns an empty TaskStore.
func NewMemoryTaskStore() *MemoryTaskStore { return &MemoryTaskStore{tasks: map[string]Task{}} }

func (s *MemoryTaskStore) CreateTask(task Task) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, exists := s.tasks[task.ID]; exists {
		return ErrInvalidTask
	}
	s.tasks[task.ID] = cloneTask(task)
	return nil
}

func (s *MemoryTaskStore) TaskByID(id string) (Task, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	task, ok := s.tasks[id]
	if !ok {
		return Task{}, ErrTaskNotFound
	}
	return cloneTask(task), nil
}

func (s *MemoryTaskStore) TasksByProject(projectID string) ([]Task, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	var tasks []Task
	for _, task := range s.tasks {
		if task.ProjectID == projectID {
			tasks = append(tasks, cloneTask(task))
		}
	}
	return tasks, nil
}

func (s *MemoryTaskStore) TasksByPersona(projectID, personaID string) ([]Task, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	var tasks []Task
	for _, task := range s.tasks {
		if task.ProjectID == projectID && task.Persona.ID == personaID {
			tasks = append(tasks, cloneTask(task))
		}
	}
	return tasks, nil
}

func (s *MemoryTaskStore) TasksByDocument(projectID, documentID string) ([]Task, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	var tasks []Task
	for _, task := range s.tasks {
		if task.ProjectID == projectID && task.TargetDocumentID == documentID {
			tasks = append(tasks, cloneTask(task))
		}
	}
	return tasks, nil
}

func (s *MemoryTaskStore) UpdateTask(task Task) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, exists := s.tasks[task.ID]; !exists {
		return ErrTaskNotFound
	}
	s.tasks[task.ID] = cloneTask(task)
	return nil
}

func (s *MemoryTaskStore) BeginTaskRun(taskID, runID string, content []byte, now time.Time) (Task, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	task, ok := s.tasks[taskID]
	if !ok {
		return Task{}, ErrTaskNotFound
	}
	index := -1
	for i := range task.Runs {
		if task.Runs[i].ID == runID {
			index = i
			break
		}
	}
	if index < 0 || task.Runs[index].State != TaskStateQueued || task.State != TaskStateQueued {
		return Task{}, ErrTaskNotRunnable
	}
	var updated Task
	_ = json.Unmarshal(content, &updated)
	s.tasks[taskID] = cloneTask(updated)
	return cloneTask(updated), nil
}

func (s *MemoryTaskStore) BumpHeartbeat(taskID string, _ time.Time) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, ok := s.tasks[taskID]; !ok {
		return ErrTaskNotFound
	}
	return nil
}

func (s *MemoryTaskStore) ReapStaleTasks(before time.Time) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	for id, task := range s.tasks {
		if task.State == TaskStateRunning {
			// In-memory store has no heartbeat tracking; use the task's
			// UpdatedAt as a proxy. If the task has been running longer
			// than the stale threshold, transition it back to queued.
			if task.UpdatedAt.Before(before) {
				task.State = TaskStateQueued
				task.UpdatedAt = time.Now()
				s.tasks[id] = cloneTask(task)
			}
		}
	}
	return nil
}

func cloneTask(task Task) Task {
	raw, _ := json.Marshal(task)
	var clone Task
	_ = json.Unmarshal(raw, &clone)
	return clone
}
