export const STALE_BASELINE_RECORDS = [
  ["accessors-are-observational", "src/lib/model/client/workspace-state/methods/document-runtime.ts", "—", "documentRuntime:attach"],
  ["accessors-are-observational", "src/lib/model/client/workspace-state/methods/slide-deck-runtime.ts", "—", "slideDeckRuntime:attach"],
  ["async-command-state-lives-with-command", "src/lib/app-views/categories/new-tab/content/launcher.svelte", "—", "inline async handler:762ea1c9752a2dd0"],
  ["constructed-client-object-has-a-consumer", "src/lib/model/client/spreadsheet-runtimes", "—", "spreadsheet-runtimes"],
  ["constructed-subject-runtime-is-reachable", "src/lib/model/client/spreadsheet-runtimes", "—", "spreadsheet-runtimes"],
  ["legacy-schema-support-does-not-exist", "src/lib/representation/data/behavior/documents/typography.ts", "—", "LEGACY_RATIO_CEILING"],
  ["legacy-schema-support-does-not-exist", "src/lib/representation/data/behavior/slide-decks/normalize.ts", "—", "legacy,legacy-slide-element"],
  ["legacy-schema-support-does-not-exist", "src/lib/representation/data/types/collaboration/anchor.ts", "—", "LegacyTextAnchor"],
  ["multi-write-capability-uses-a-unit-of-work", "src/lib/capabilities/document/api/submit-document-changes/submit-document-changes.ts", "—", "update,create,create,update,update,update"],
  ["multi-write-capability-uses-a-unit-of-work", "src/lib/capabilities/project-resources/api/create-project-resource/create-project-resource.ts", "—", "create,create,create,create"],
  ["multi-write-capability-uses-a-unit-of-work", "src/lib/capabilities/slide-deck/api/submit-slide-deck-changes/submit-slide-deck-changes.ts", "—", "create,update,update,update"],
  ["production-views-have-no-fixture-repositories", "src/lib/app-views/categories/spreadsheet-editor/content/sheet.svelte", "—", "fake-read::"],
  ["remounted-views-hold-no-declared-tab-state", "src/lib/app-views/categories/spreadsheet-editor/content/sheet.svelte", "state-is-classified", "selected,zoom"],
  ["resource-id-selects-the-rendered-body", "src/lib/app-views/categories/spreadsheet-editor/content", "source-flow", "spreadsheet"],
  ["runtime-lifecycle-follows-tabs", "src/lib/model/client/workspace-state/methods/document-runtime.ts", "—", "attach:state.documents"],
  ["runtime-lifecycle-follows-tabs", "src/lib/model/client/workspace-state/methods/slide-deck-runtime.ts", "—", "attach:state.decks"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/document-runtimes", "close-releases", "document"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/slide-deck-runtimes", "close-releases", "slide-deck"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/spreadsheet-runtimes", "close-releases", "spreadsheet"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/workspace-state", "contract-exists", "document"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/workspace-state", "contract-exists", "slide-deck"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/workspace-state", "contract-exists", "spreadsheet"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/document-runtimes", "open-acquires", "document"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/slide-deck-runtimes", "open-acquires", "slide-deck"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/spreadsheet-runtimes", "open-acquires", "spreadsheet"],
  ["runtime-open-close-is-balanced", "src/lib/model/client/spreadsheet-runtimes", "workspace-reaches-runtime", "spreadsheet"],
  ["source-complexity-is-reviewed", "src/lib/app-views/categories/project-overview/content/overview.svelte", "—", "svelte-script:over-300"],
  ["unsupported-subject-is-explicit", "src/lib/app-views/categories/context-editor/content", "non-live-is-visible", "context-editor:unavailable"]
] as const;
