export const TYPE_DIAGNOSTICS = [
  ["F1", "src/lib/capabilities/semantic-overlay/api/shared/resource.ts", "8:40", "deleted slide normalizer import"],
  ["F4", "src/lib/capabilities/project-resources/api/create-project-resource/create-project-resource.ts", "158:3", "accepted literal widened to boolean"],
  ["F3", "src/lib/capabilities/templates/api/shared/bodies.ts", "246:74", "TemplateCell BlockFormat is not CellFormat"],
  ["F3", "src/lib/capabilities/templates/api/shared/bodies.ts", "288:7", "format rule lacks id and current CellFormat"],
  ["F1", "src/lib/capabilities/templates/api/shared/validation.ts", "6:40", "deleted slide normalizer import"],
  ["F2", "src/lib/capabilities/templates/api/instantiate-template/instantiate-template.ts", "4:43", "deleted document typography import"],
  ["F1", "src/lib/capabilities/templates/api/instantiate-template/instantiate-template.ts", "5:38", "slide readiness imported from deleted module"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "12:40", "deleted slide normalizer import"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "201:42", "candidate type lost downstream"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "339:45", "slide type lost downstream"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "340:87", "slide type lost downstream"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "340:94", "offset type lost downstream"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "401:41", "candidate type lost downstream"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "461:40", "notes block type lost downstream"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "495:41", "candidate type lost downstream"],
  ["F1", "src/lib/capabilities/derived-output/api/shared/resource-reading.ts", "563:46", "candidate type lost downstream"],
  ["F1", "src/lib/capabilities/research-chat/api/shared/reading-tools.ts", "4:40", "deleted slide normalizer import"],
  ["F1", "src/lib/capabilities/research-chat/api/shared/reading-tools.ts", "136:37", "candidate type lost downstream"]
] as const;

export const IMPORT_BLOCKED_SUITES = [
  "src/test/keys-route.test.ts",
  "test/unit/semantic-derived-output-flow.test.ts",
  "src/lib/capabilities/derived-output/test/non-functional/live-derived-output.test.ts",
  "src/lib/capabilities/derived-output/test/unit/derived-output.test.ts",
  "src/lib/capabilities/derived-output/test/unit/resource-reading.test.ts",
  "src/lib/capabilities/document/test/unit/document.test.ts",
  "src/lib/capabilities/project-resources/test/non-functional/create-project-resource-atomicity.test.ts",
  "src/lib/capabilities/project-resources/test/unit/project-resources.test.ts",
  "src/lib/capabilities/research-chat/test/unit/research-chat.test.ts",
  "src/lib/capabilities/semantic-overlay/test/unit/semantic-external-text.test.ts",
  "src/lib/capabilities/semantic-overlay/test/unit/semantic-material-sync.test.ts",
  "src/lib/capabilities/semantic-overlay/test/unit/semantic-overlay.test.ts",
  "src/lib/capabilities/templates/test/non-functional/instantiate-template-atomicity.test.ts",
  "src/lib/capabilities/templates/test/non-functional/remove-template-atomicity.test.ts",
  "src/lib/capabilities/templates/test/unit/answers.test.ts",
  "src/lib/capabilities/templates/test/unit/stages.test.ts",
  "src/lib/capabilities/templates/test/unit/templates.test.ts",
  "src/lib/model/client/workspace-state/test/non-functional/runtime-lifecycle.test.ts",
  "src/lib/model/client/workspace-state/test/unit/persistence.test.ts",
  "src/lib/model/client/workspace-state/test/unit/single-flight.test.ts",
  "src/lib/model/client/workspace-state/test/unit/workspace-state.test.ts",
  "src/lib/app-views/categories/document-editor/procedures/test/unit/annotations.test.ts",
  "src/lib/app-views/categories/document-editor/procedures/test/unit/comments.test.ts",
  "src/lib/app-views/categories/document-editor/procedures/test/unit/templating.test.ts",
  "src/lib/app-views/categories/project-overview/procedures/test/unit/contexts.test.ts",
  "src/lib/app-views/categories/presentation-editor/procedures/test/unit/templating.test.ts",
  "src/lib/app-views/categories/templates/procedures/test/unit/library.test.ts"
] as const;
